version: "3.7"

services:
    cheshire-cat-core:
        image: ghcr.io/cheshire-cat-ai/core:latest
        environment:
          - PYTHONUNBUFFERED=1
          - WATCHFILES_FORCE_POLLING=true
          - CORE_HOST=${CORE_HOST:-localhost}
          - CORE_PORT=${CORE_PORT:-1865}
          - CORE_USE_SECURE_PROTOCOLS=${CORE_USE_SECURE_PROTOCOLS:-}
          - API_KEY=${API_KEY:-}
          - LOG_LEVEL=${LOG_LEVEL:-WARNING}
          - DEBUG=${DEBUG:-true}
          - SAVE_MEMORY_SNAPSHOTS=${SAVE_MEMORY_SNAPSHOTS:-false}
    nginx:
      build: ./nginx
      container_name: cheshire_cat_nginx
      ports:
        - 80:80
      depends_on:
        - cheshire-cat-core